web:
  restart: always
  build: ./pyweb
  expose:
    - "9090"
  links:
    - mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: /usr/local/bin/gunicorn -w 2 -b :9090 server:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "9090:80"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - web
  links:
    - web

nharvest:
  build: ./pymysql/
  links:
    - mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - .:/code

mysql:
   image: mysql:latest
   volumes:
      - ./data/mysql:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: Rvpooh123
     MYSQL_DATABASE: sft
     MYSQL_USER: sft
     MYSQL_PASSWORD: sft