web:
  restart: always
  build: ./pyweb
  expose:
    - "8009"
  links:
    - db
  volumes:
    - /etc/localtime:/etc/localtime:ro
  command: /usr/local/bin/gunicorn -w 2 -b :8009 server:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8009:80"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - web
  links:
    - web

harvest:
   build: ./pyimage/
   links:
    - db
   volumes:
    - /etc/localtime:/etc/localtime:ro
    - .:/code

nharvest:
  build: ./pymysql/
  links:
    - mysql
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - .:/code

db:
   image: mongo:latest
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - './save/:/save'
     - './data:/data/db'

mysql:
   image: mysql:latest
   volumes:
      - ./data/mysql:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: Rvpooh123
     MYSQL_DATABASE: sft
     MYSQL_USER: sft
     MYSQL_PASSWORD: sft